site_name: My Docs

nav:
  - Home: index.md
  - Architecture Reference:
      - archit_ref.md
      - docs-reverse-engineering/control-flow-graph-and-type-checking.md
      - docs-reverse-engineering/type-narrowing-deep-dive.md

theme:
  name: mkdocs
  user_color_mode_toggle: true
  # hljs_style: vs2015

markdown_extensions:
  - footnotes

extra_css:
  - ./extra.css
